name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        check-latest: true
        registry-url: 'https://registry.npmjs.org'

    - name: Debug environment
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Top of package.json:" && head -n 30 package.json || true
        echo "Top of package-lock.json:" && head -n 30 package-lock.json || true

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      env:
        NPM_CONFIG_AUDIT: 'false'
        NPM_CONFIG_FUND: 'false'
      run: |
        npm install --no-audit --no-fund --verbose

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./.vitepress/dist
        force_orphan: true
